---
version: "3"
services:
 devopsdb:
   container_name: devopsdb
   image: viswanathkasi/dbimage
   ports:
     - "3306:3306"

 application:
   image: viswanathkasi/appimage
   container_name: containerapp
   ports:
     - "5000:8080"
   depends_on:
     - "devopsdb"
