---
version: "3"
services:
 devopsdb:
   image: viswanathkasi/java-stack-dbimage
   ports:
     - "3306:3306"
   deploy:
     replicas: 1

 application:
   image: viswanathkasi/java-stack-appimage
   ports:
     - "8081:8080"
   deploy:
     replicas: 3
   depends_on:
     - "devopsdb"
