---
version: "3"
services:
 devopsdb:
   image: viswanathkasi/dummy:db
   ports:
     - "3306:3306"
   deploy:
     replicas: 1
   networks:
     - stack

 application:
   image: viswanathkasi/dummy:app
   ports:
     - "8081:8080"
   deploy:
     replicas: 3
   depends_on:
     - "devopsdb"
   networks:
     - stack

networks:
  stack:
    driver: overlay
